const qBank = [
    { id: 1, 
        question: "What is the capital of Maharashtra?", 
        options: ["Pune", "Mumbai", "Nagpur", "Nashik"], 
        answer: "Mumbai", 
    },
    { id: 2, 
        question: "Which city is known as the Pink City of India?", 
        options: ["Jaipur", "Jodhpur", "Udaipur", "Bikaner"], 
        answer: "Jaipur", 
    },
    { id: 3, 
        question: "Which river is known as the longest river in India?", 
        options: ["Yamuna", "Godavari", "Ganga", "Narmada"], 
        answer: "Ganga", 
    },
    { id: 4, 
        question: "Where is the Taj Mahal located?", 
        options: ["Delhi", "Agra", "Jaipur", "Lucknow"], 
        answer: "Agra", 
    },
    { id: 5, 
        question: "What is the capital of Rajasthan?", 
        options: ["Jodhpur", "Udaipur", "Jaipur", "Ajmer"], 
        answer: "Jaipur", 
    },
    { id: 6,
        question: "Which monument is located in Delhi and was built by Shah Jahan?", 
        options: ["Red Fort", "India Gate", "Qutub Minar", "Lotus Temple"], 
        answer: "Red Fort", 
    },
]