const qBank = [
    { id: 1, 
        question: "What is the capital of Maharashtra?", 
        options: ["Pune", "Mumbai", "Nagpur", "Nashik"], 
        answer: "Mumbai", 
    },
    { id: 2, 
        question: "Which city is known as the Pink City of India?", 
        options: ["Jaipur", "Jodhpur", "Udaipur", "Bikaner"], 
        answer: "Jaipur", 
    },
    { id: 3, 
        question: "Which river is known as the longest river in India?", 
        options: ["Yamuna", "Godavari", "Ganga", "Narmada"], 
        answer: "Ganga", 
    },
    { id: 4, 
        question: "Where is the Taj Mahal located?", 
        options: ["Delhi", "Agra", "Jaipur", "Lucknow"], 
        answer: "Agra", 
    },
    { id: 5, 
        question: "What is the capital of Rajasthan?", 
        options: ["Jodhpur", "Udaipur", "Jaipur", "Ajmer"], 
        answer: "Jaipur", 
    },
    { id: 6,
        question: "Which monument is located in Delhi and was built by Shah Jahan?", 
        options: ["Red Fort", "India Gate", "Qutub Minar", "Lotus Temple"], 
        answer: "Red Fort", 
    },
    { id: 7, 
        question: "Which is the highest mountain peak in India?", 
        options: ["Nanda Devi", "Kanchenjunga", "Mount Everest", "Annapurna"], 
        answer: "Kanchenjunga", 
    },
    { id: 8, 
        question: "Which Indian city is famous for the Golden Temple?", 
        options: ["Amritsar", "Chandigarh", "Ludhiana", "Patiala"], 
        answer: "Amritsar", 
    },
    { id: 9, 
        question: "What is the capital of West Bengal?", 
        options: ["Darjeeling", "Kolkata", "Siliguri", "Howrah"], 
        answer: "Kolkata", 
    },
    { id: 10, 
        question: "Which river flows through the city of Varanasi?", 
        options: ["Yamuna", "Ganga", "Godavari", "Krishna"], 
        answer: "Ganga", 
    },
    { id: 11, 
        question: "Which temple is famous for its Rath Yatra festival?", 
        options: ["Jagannath Temple", "Meenakshi Temple", "Kedarnath Temple", "Somnath Temple"], 
        answer: "Jagannath Temple", 
    },
    {
     id: 12,
     question: "Which is the largest state in India by area?",
     options: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Uttar Pradesh"],
     answer: "Rajasthan", 
    },
    { 
        id: 13,
        question: "Where is the Gateway of India located?",
        options: ["Mumbai", "Kolkata", "Chennai", "Goa"],
        answer: "Mumbai",
    },
    { 
        id: 14,
        question: "Which Indian state is famous for its backwaters?",
        options: ["Kerala", "Goa", "Odisha", "Assam"],
    },
    {
        id: 15,
        question: "What is the capital of Gujarat?",
        options: ["Ahmedabad", "Surat", "Vadodara", "Gandhinagar"],
        answer: "Gandhinagar",
    },
    { 
        id: 16,
        question: "Which monument is also known as the 'Symbol of Love'?",
        options: ["Red Fort", "Taj Mahal", "Qutub Minar", "Charminar"],
        answer: "Taj Mahal", 
    },
    { 
        id: 17,
]

